application: ground-control-714
version: 1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: generated/index.html
  upload: generated/index.html

- url: /(.*\.html)
  static_files: generated/\1
  upload: generated/(.*\.html)

- url: /(apple-touch-icon-precomposed\.png|favicon\.ico|humans\.txt|robots\.txt|sitemap\.xml)
  static_files: static/\1
  upload: static/(apple-touch-icon-precomposed\.png|favicon\.ico|humans\.txt|robots\.txt|sitemap\.xml)

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /.*
  static_files: static/404.html
  upload: static/404.html

skip_files:
- \.git/.*
- pages/.*
- raw assets/.*
- templates/.*
- ^(.*/)?\.gitattributes$
- ^(.*/)?\.gitignore$
- ^(.*/)?\.sublime-project$
- ^(.*/)?\.sublime-workspace$
- ^(.*/)?\.bat$